# Generated by Django 5.0.3 on 2024-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
