# Generated by Django 5.0.3 on 2024-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
